### PR TITLE
complete documentation

### PR DESCRIPTION
**Pull request by zvezdochiot**
* documentation by shelves
* added man
* added LICENSE (PDM 1.0)
* optimize source code
* command interface merged
* added undither (linear OLS)
* added generation pattern
* update manual (undither)

### CODE REVIEW

**Comment by zvezdochiot** [comment]
@Soreine, please update the documentation under 0.0.87, I do not speak English well.

**Comment by zvezdochiot** [comment]
@Soreine, please update the documentation under 0.0.90, I do not speak English well.

**Comment by Soreine** [comment]
I'm away from my computer this week. I'll take care of it afterward.

**Comment by zvezdochiot** [comment]
16.05.2021 No answer.

**Pull request closed without merging**
